<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Generate\Api\Representation\GenerationRepresentation $generation
 * @var array $templateProperties
 *
 * For loop:
 * @var \Omeka\View\Helper\Api $api
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * @var string $baseUrlFiles
 * @var string $mode
 * @var bool $isSiteRequest
 * @var string $labelInfo
 * @var bool $showLocale
 *
 * @var array $values
 * @var bool $isSub
 * @var ?int $indexValuesMedia
 */
?>

<?php if ($isSub): ?>
<dl class="generation-media">
    <h4 class="generation-media-label"><?= sprintf($isSiteRequest ? $translate('File #%s') : $translate('Media #%s'), $this->partialLoop()->getPartialCounter()) ?></h4>
<?php else: ?>
<dl class="generation">
<?php endif; ?>

<?php foreach ($values as $term => $propertyData): ?>
    <?php if (empty($propertyData['generations'])) continue; ?>
    <div class="property">
        <dt>
            <?= $escape($propertyData['alternate_label'] ?: $translate($propertyData['property']->label())) ?>
            <?php if (!isset($propertyData['property'])):?>
            <?php // Nothing to do (file). ?>
            <?php elseif ('term' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </dt>
        <?php foreach ($propertyData['generations'] as $generationData):
            if (!empty($generationData['empty'])) continue;
            $valueType = $generationData['type'];
            $valueBaseType = $generationData['basetype'];
            $valueLang = $generationData['lang'] ?? '';
            $class = ['value'];
            // TODO Improve.
            if ($valueBaseType === 'resource') {
                $class[] = 'resource';
                // Only item is supported for now.
                $class[] = substr($valueType, 0, 9) === 'resource:' ? substr($valueType, 9) : 'item';
            } elseif ($valueBaseType === 'uri') {
                $class[] = 'uri';
            }
            ?>
        <dd class="<?= implode(' ', $class) ?>" lang="<?= $escape($valueLang) ?>">
            <?php if ($showLocale && $valueLang): ?>
            <span class="language"><?= $valueLang ?></span>
            <?php endif; ?>
            <?php if (!empty($generationData['new'])): ?>
            <span class="value-content"><?php
                    if ($valueBaseType === 'uri'):
                        echo $escape($generationData['proposed']['@uri'] . ' / ' . $generationData['proposed']['@label']);
                    elseif ($valueBaseType === 'resource'):
                        try {
                            $res = $api->read('resources', ['id' => $generationData['proposed']['@resource']])->getContent();
                            echo $res->link($res->displayTitle());
                        } catch (\Exception $e) {
                            echo sprintf($translate('%s [unavailable]'), $generationData['proposed']['@resource']);
                        }
                    elseif ($term === 'file'): // File is always a new value.
                        echo isset($generationData['proposed']['store'])
                            ? '<a href="' . $escapeAttr($baseUrlFiles . '/generation/' . $generationData['proposed']['store']) . '" download="download" target="_self">' . $escape($generationData['proposed']['@value']) . '</a>'
                            : sprintf('%s [missing file]', $escape($generationData['proposed']['@value']));
                    else:
                        echo $escape($generationData['proposed']['@value']);
                    endif;
            ?></span>
                <?php else: ?>
            <dl>
                <dd>
                    <?php if ($valueBaseType === 'uri'):
                        echo $escape($generationData['original']['@uri'] . ' / ' . $generationData['original']['@label']);
                    elseif ($valueBaseType === 'resource'):
                        try {
                            $res = $api->read('resources', ['id' => $generationData['original']['@resource']])->getContent();
                            echo $res->link($res->displayTitle());
                        } catch (\Exception $e) {
                            echo sprintf($translate('%s [unavailable]'), $generationData['original']['@resource']);
                        };
                    else:
                        echo $escape($generationData['original']['@value']);
                    endif; ?>
                </dd>
                <dd>
                    <?php if ($valueBaseType === 'uri'):
                        echo $escape($generationData['proposed']['@uri'] . ' / ' . $generationData['proposed']['@label']);
                    elseif ($valueBaseType === 'resource'):
                        try {
                            $res = $api->read('resources', ['id' => $generationData['proposed']['@resource']])->getContent();
                            echo $res->link($res->displayTitle());
                        } catch (\Exception $e) {
                            echo sprintf($translate('%s [unavailable]'), $generationData['proposed']['@resource']);
                        }
                    else:
                        echo $escape($generationData['proposed']['@value']);
                    endif; ?>
                </dd>
            </dl>
            <?php endif; ?>
        </dd>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>

<?php if ($isSub): ?>
</dl>
<?php else: ?>
</dl>
<?php endif; ?>
