<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AiGenerator\Api\Representation\AiRecordRepresentation $aiRecord
 * @var \AiGenerator\Api\Representation\AiRecordRepresentation $resource
 * @var array $templateProperties
 * @var array $values
 * @var array $valuesMedias
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$setting = $plugins->get('setting');
$labelInfo = $setting('property_label_information');
$showLocale = true;
?>

<dl class="ai-record">

<?php foreach ($values as $term => $propertyData): ?>
    <?php if (empty($propertyData['ai_records'])) continue; ?>
    <div class="property">
        <dt>
            <?= $escape($propertyData['alternate_label'] ?: $translate($propertyData['property']->label())) ?>
            <?php if (!isset($propertyData['property'])):?>
            <?php // Nothing to do (file). ?>
            <?php elseif ('term' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
            <?php endif; ?>
        </dt>
        <?php foreach ($propertyData['ai_records'] as $aiRecordData):
            if (!empty($aiRecordData['empty'])) continue;
            $valueType = $aiRecordData['type'];
            $valueBaseType = $aiRecordData['basetype'];
            $valueLang = $aiRecordData['lang'] ?? '';
            $class = ['value'];
            // TODO Improve.
            if ($valueBaseType === 'resource') {
                $class[] = 'resource';
                // Only item is supported for now.
                $class[] = substr($valueType, 0, 9) === 'resource:' ? substr($valueType, 9) : 'item';
            } elseif ($valueBaseType === 'uri') {
                $class[] = 'uri';
            }
            ?>
        <dd class="<?= implode(' ', $class) ?>" lang="<?= $escape($valueLang) ?>">
            <?php if ($showLocale && $valueLang): ?>
            <span class="language"><?= $valueLang ?></span>
            <?php endif; ?>
            <?php if (!empty($aiRecordData['new'])): ?>
            <span class="value-content"><?php
                    if ($valueBaseType === 'uri'):
                        echo $escape($aiRecordData['proposed']['@uri'] . ' / ' . $aiRecordData['proposed']['@label']);
                    elseif ($valueBaseType === 'resource'):
                        try {
                            $res = $api->read('resources', ['id' => $aiRecordData['proposed']['@resource']])->getContent();
                            echo $res->link($res->displayTitle());
                        } catch (\Exception $e) {
                            echo sprintf($translate('%s [unavailable]'), $aiRecordData['proposed']['@resource']);
                        }
                    else:
                        echo $escape($aiRecordData['proposed']['@value']);
                    endif;
            ?></span>
                <?php else: ?>
            <dl>
                <dd>
                    <?php if ($valueBaseType === 'uri'):
                        echo $escape($aiRecordData['original']['@uri'] . ' / ' . $aiRecordData['original']['@label']);
                    elseif ($valueBaseType === 'resource'):
                        try {
                            $res = $api->read('resources', ['id' => $aiRecordData['original']['@resource']])->getContent();
                            echo $res->link($res->displayTitle());
                        } catch (\Exception $e) {
                            echo sprintf($translate('%s [unavailable]'), $aiRecordData['original']['@resource']);
                        };
                    else:
                        echo $escape($aiRecordData['original']['@value']);
                    endif; ?>
                </dd>
                <dd>
                    <?php if ($valueBaseType === 'uri'):
                        echo $escape($aiRecordData['proposed']['@uri'] . ' / ' . $aiRecordData['proposed']['@label']);
                    elseif ($valueBaseType === 'resource'):
                        try {
                            $res = $api->read('resources', ['id' => $aiRecordData['proposed']['@resource']])->getContent();
                            echo $res->link($res->displayTitle());
                        } catch (\Exception $e) {
                            echo sprintf($translate('%s [unavailable]'), $aiRecordData['proposed']['@resource']);
                        }
                    else:
                        echo $escape($aiRecordData['proposed']['@value']);
                    endif; ?>
                </dd>
            </dl>
            <?php endif; ?>
        </dd>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>

</dl>
