<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var bool $skipGenerateCss
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');

$js = 'const siteBaseUrl = ' . json_encode(substr($url($space === 'guest' ? 'site/guest/generation-id' : 'site/generation-id', ['action' => 'delete', 'resource' => 'generation', 'id' => 0], true), 0, -8), 320) . ';
const confirmFormCsrf = ' . json_encode($site->getServiceLocator()->get('FormElementManager')->get(\Omeka\Form\ConfirmForm::class)->prepare()->get('confirmform_csrf')->getValue()) . ';';

if (empty($skipGenerateCss)) {
    $this->headLink()
        ->appendStylesheet($assetUrl('css/generate.css', 'Generate'));
}
$this->headScript()
    ->appendFile($assetUrl('js/generate.js', 'Generate'), 'text/javascript', ['defer' => 'defer'])
    ->appendScript($js);
