<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User|null $user
 * @var \Generate\Form\GenerateForm $form
 * @var \AdvancedResourceTemplate\Api\Representation\ResourceTemplateRepresentation|null $resourceTemplate
 * @var \Generate\Api\Representation\GenerationRepresentation|null $generation
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var array $fields
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation|null $templateMedia A sub template for media may have no fields.
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" (for template select or for show readonly form before submit) or "write"
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$generationForm = $plugins->get('generationForm');

$this->htmlElement('body')->appendAttribute('class', 'edit items ' . $this->params()->fromRoute('resource') . ' resource');

if ($form) $form->prepare();

$mapLabels = [
    'generations' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="generate-resource conbribute-add container <?= $space && $space !== 'default' ? $space : '' ?>">

    <?= $this->pageTitle($resource ? $escape($resource->displayTitle()) : sprintf($translate('Add %s'), $translate($mapLabels['items'])), 2) ?>
    <h3><?= $resource ? sprintf($translate('Edit %s'), $translate($mapLabels[$resource->resourceName()])) : sprintf($translate('New %s'), $translate($mapLabels['items'])) ?></h3>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php if (count($fields) && $form):
        // The two lists of fields are merged in one form by default.
        $this->trigger("view.$action.before");
        echo $generationForm([
            'site' => $site,
            'user' => $user,
            'form' => $form,
            'resourceTemplate' => $resourceTemplate,
            'generation' => $generation,
            'resource' => $resource,
            'fields' => $fields,
            'templateMedia' => $templateMedia,
            'fieldsByMedia' => $fieldsByMedia,
            'fieldsMediaBase' => $fieldsMediaBase,
            'action' => $action,
            'mode' => $mode,
            'space' => $space,
            'submitLabel' => $action === 'add' && $setting('generate_allow_update') !== 'no' ? $translate('Add') : $translate('Submit'),
            'cancelLabel' => $translate('Cancel'),
            'isMainForm' => true,
            'skipGenerateCss' => false,
        ]);
        $this->trigger("view.$action.after");

    elseif ($action === 'add' && $form): // First step form to select a resource template.
        if ($mode === 'read') {
            $form->remove('submit');
            echo $this->form($form);
        } else {
            $form->get('submit')->setValue('Select'); // @translate
            echo $this->form($form);
        }

    else: ?>
    <div class="messages">
        <p><?= $translate('A template with fields is required to submit a document. Ask the administrator for more information.') ?></p>
    </div>

    <?php endif; ?>

</div>
