<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Generate\Api\Representation\GenerationRepresentation|null $generation
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Medias are displayed through displayValues() for now.
// $medias = $generation->valuesMedias();
// $embedMedia = $siteSetting('item_media_embed', false);

$siteSlug = $this->params()->fromRoute('site-slug');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;

$this->vars()->offsetSet('skipGenerateCss', false);
$partial('generate/site/generation/asset-include');

$this->htmlElement('body')->appendAttribute('class', 'generation resource show');
?>

<div class="generate-resource conbribute-show container <?= $space && $space !== 'default' ? $space : '' ?>">

    <?= $this->pageTitle($generation->displayTitle(null, $lang), 2) ?>
    <h3><?= $translate('Generation') ?></h3>

    <ul class="generation-status">
        <li class="generation-resource"><?= $resource ? $resource->linkPretty() : $escape($translate('No resource')) ?></li>
        <li class="submitted"><?= $escape($generation->isSubmitted() ? $translate('Is submitted') : $translate('Is not submitted')) ?></li>
        <li class="reviewed"><?= $escape($generation->isReviewed() ? $translate('Is reviewed') : $translate('Is not reviewed')) ?></li>
    </ul>

    <?php if ($msgs = $this->messages()): ?>
    <div class="messages">
        <?= $msgs ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.before'); ?>

    <?= $generation->displayValues() ?>

    <?php if ($generation->isUpdatable()): ?>
    <ul class="actions" data-message-remove-generation="<?= $escapeAttr($translate('Are you sure to remove this generation?')) ?>">
        <?php if ($generation->userIsAllowed('update')): ?>
        <li><a class="o-icon-edit button edit-button edit-generation" href="<?= $escapeAttr($generation->siteUrl($siteSlug, false, 'edit', $space === 'guest')) ?>"><?= $escape($translate('Edit')) ?></a></li>
        <?php endif; ?>
        <li><a class="o-icon-submit button submit-button submit-generation" href="<?= $escapeAttr($generation->siteUrl($siteSlug, false, 'submit', $space === 'guest')) ?>"><?= $escape($translate('Submit')) ?></a></li>
        <?php if ($generation->userIsAllowed('delete')): ?>
        <li><a class="o-icon-delete button delete-button remove-generation" data-generation-id="<?= $generation->id() ?>" data-generation-url="<?= $escapeAttr($generation->siteUrl($siteSlug, false, 'delete', $space === 'guest')) ?>" data-redirect-url="<?= $escapeAttr($url('site', [], true)) ?>" href="#"><?= $escape($translate('Delete')) ?></a></li>
        <?php endif; ?>
    </ul>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>

</div>
