<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Generate\Form\GenerateForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Generate\Api\Representation\GenerationRepresentation[] $generations
 * @var \Generate\Api\Representation\TokenRepresentation[] $unusedTokens
 * @var string $siteSlug
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="generations">
    <?php $totalTokens = $api->search('generation_tokens', ['resource_id' => $resource->id(), 'limit' => 0])->getTotalResults(); ?>
    <?php if (empty($totalTokens)): ?>
        <?php if (in_array($setting('generate_mode'), ['user_token', 'token'])): ?>
    <div class="no-resources no-tokens">
        <p><?= $translate('There are no tokens for this resource or generation mode doesn’t use token.') ?></p>
    </div>
        <?php endif; ?>
    <?php else: ?>
    <?php $totalExpiredTokens = $api
        ->search(
            'generation_tokens',
            ['resource_id' => $resource->id(), 'datetime' => [['field' => 'expire', 'type' => 'lt', 'value' => date('Y-m-d H:i:s')]]]
        )
        ->getTotalResults(); ?>
    <div class="generation-token">
        <p><?= sprintf($translate('There are %d tokens for this resource (%d expired).'), $totalTokens, $totalExpiredTokens) ?></p>
        <?php if (($totalTokens - $totalExpiredTokens) && $this->userIsAllowed('Generate\Controller\Admin\Generation', 'expire-tokens')): ?>
        <?= $hyperlink($translate('Expire all tokens'), $this->url('admin/generation/id', ['action' => 'expire-tokens', 'id' => $resource->id()]), ['class' => 'button']) ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>

<?php if (empty($generations)): ?>
    <div class="no-resources no-generations">
        <p><?= $translate('There are no generations for this resource.') ?></p>
    </div>
<?php else: ?>
<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
    'item-set' => \Omeka\Api\Adapter\MediaAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');
?>
<?php foreach ($generations as $generation): ?>
<?php $token = $generation->token(); ?>
<div class="generation">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?= $translate('Generation') ?>
                <?php /*
                <span class="generation-id">#<?= $generation->id() ?></span>
                */ ?>
                <?php if ($email = $generation->email()): ?>
                <span class="generation-email"><?= $hyperlink($email, 'mailto:' . $email) ?></span>
                <?php endif; ?>

                <span class="generation-date"><?= $this->i18n()->dateFormat($generation->created(), 'medium', 'medium') ?></span>

                <?php if ($generation->created() != $generation->modified()): // Don't use !==. ?>
                <span class="generation-date-modified"><?= $translate('(modified)') ?></span>
                <?php endif; ?>

                <?php if ($token): ?>
                <span> / </span>
                <span class="generation-token"><?= $hyperlink($token->token(), $token->siteUrl($siteSlug, true)) ?></span>
                <?php endif; ?>

                <?php if ($generation->isPatch()): // Only patchs should be validated individually. ?>

                <?php if ($editRight): ?>
                <?php // TODO Check if all values are the same to change the default icon to "validated". ?>
                <span class="single actions"><a href="#"
                    class="validate o-icon-validate"
                    data-validate-url="<?= $escape($generation->adminUrl('validate')) ?>"
                    data-status="validate"
                    aria-label="<?= $escape($translate('Validate all values')) ?>"
                    title="<?= $escape($translate('Validate all values')) ?>"></a></span>
                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?= $generation->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    data-status-toggle-url="<?= $escape($generation->adminUrl('toggle-status')) ?>"
                    data-status="<?= $generation->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    aria-label="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"
                    title="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"></a></span>
                <?php endif; ?>

                <?php if ($token && $token->isExpired()): ?>
                <span class="single no-action o-icon-expired-token" aria-label="<?= $escape($translate('Expired token')) ?>"></span>
                <?php elseif ($token): ?>
                <span class="single single-action"><a href="#"
                    class="expire-token o-icon-expire-token"
                    data-expire-token-url="<?= $escape($generation->adminUrl('expire-token')) ?>"
                    aria-label="<?= $escape($translate('Expire token')) ?>"
                    title="<?= $escape($translate('Expire token')) ?>"></a></span>
                <?php endif; ?>

                <?php else: ?>

                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?= $generation->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    data-status-toggle-url="<?= $escape($generation->adminUrl('toggle-status')) ?>"
                    data-status="<?= $generation->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    aria-label="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"
                    title="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"></a></span>

                <?php endif; ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="generation-value">
            <td>
                <?php
                $proposal = $generation->proposalNormalizeForValidation();
                $vars = $this->vars();
                $varsBase = $vars->getArrayCopy();
                $varsBase['api'] = $api;
                $varsBase['escape'] = $escape;
                $varsBase['translate'] = $translate;
                $varsBase['hyperlink'] = $hyperlink;
                $varsBase['escapeAttr'] = $escapeAttr;
                $varsBase['generation'] = $generation;
                $varsBase['editRight'] = $editRight;
                $varsBase['labelInfo'] = $setting('property_label_information');
                $varsBase['values'] = $resource->values();
                $varsBase['isSubProposal'] = false;
                $varsBase['proposal'] = $proposal;
                echo $this->partial('common/admin/generate-list-part', $varsBase);
                if (isset($proposal['media']) && count($proposal['media'])):
                    // No upper div to simplify admin theme.
                    ?>
                    <div class="generation-medias">
                        <h4 class="generation-medias-label"><?= $translate('Medias') ?></h4>
                        <?php
                        // TODO Currently, only new media are managed as sub-resource: generation for new resource, not generation for existing item with media at the same time.
                        $varsBase['values'] = [];
                        $varsBase['isSubProposal'] = true;
                        $varsForLoop = [];
                        foreach ($proposal['media'] ?? [] as $subProposal) {
                            $varsBase['proposal'] = $subProposal;
                            $varsForLoop[] = $varsBase;
                        }
                        echo $this->partialLoop('common/admin/generate-list-part', $varsForLoop);
                        ?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php endif; ?>

<?php if ($unusedTokens): ?>
<h4><?= $translate('Unused tokens') ?></h4>
<?= $this->partial('common/admin/generate-token-list', [
    'resource' => $resource,
    'tokens' => $unusedTokens,
    'siteSlug' => $siteSlug,
]) ?>
<?php endif; ?>

</div>
