<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Generate\Form\GenerateForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Generate\Api\Representation\GeneratedResourceRepresentation[] $generatedResources
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="generated-resources">

<?php if (empty($generatedResources)): ?>

    <div class="no-resources no-generated-resources">
        <p><?= $translate('There are no generated resources for this resource.') ?></p>
    </div>

<?php else: ?>

<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');

$labelInfo = $setting('property_label_information');
?>
<?php foreach ($generatedResources as $generatedResource): ?>
<div class="generated-resource">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?= $translate('Generated resource') ?>
                <?php /*
                <span class="generated-resource-id">#<?= $generatedResource->id() ?></span>
                */ ?>

                <span class="generated-resource-date"><?= $this->i18n()->dateFormat($generatedResource->created(), 'medium', 'medium') ?></span>

                <?php if ($generatedResource->created() != $generatedResource->modified()): // Don't use !==. ?>
                <span class="generated-resource-date-modified"><?= $translate('(modified)') ?></span>
                <?php endif; ?>

                <?php if ($editRight): ?>
                <?php // TODO Check if all values are the same to change the default icon to "validated". ?>
                <span class="single actions"><a href="#"
                    class="validate o-icon-validate"
                    data-validate-url="<?= $escape($generatedResource->adminUrl('validate')) ?>"
                    data-status="validate"
                    aria-label="<?= $escape($translate('Validate all values')) ?>"
                    title="<?= $escape($translate('Validate all values')) ?>"></a></span>
                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?= $generatedResource->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    data-status-toggle-url="<?= $escape($generatedResource->adminUrl('toggle-status')) ?>"
                    data-status="<?= $generatedResource->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    aria-label="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"
                    title="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"></a></span>
                <?php endif; ?>

            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="generated-resource-value">
            <td>
                <?php
                $proposal = $generatedResource->proposalNormalizeForValidation();
                $values = $resource->values();
                /** @var \Omeka\Api\Representation\ResourceTemplateRepresentation $resourceTemplate */
                $resourceTemplate = $proposal['template'] ?? null;
                // Clean data for the special keys.
                unset($proposal['template'], $proposal['media']);

                ?>
                <dl>
                    <div class="property">
                        <dt><?= $escape($translate('Resource template')) ?></dt>
                        <dd class="values">
                            <span class="resource-template"><?= $escape($resourceTemplate ? $resourceTemplate->label() : $translate('No resource template')) ?></span>
                        </dd>
                    </div>
                </dl>

                <dl>
                <?php foreach ($proposal as $term => $propositions):
                    if (isset($values[$term])) {
                        $propertyData = $values[$term];
                    } elseif ($term === 'file') {
                        $propertyData = [
                            'property' => null,
                            'alternate_label' => $translate('File'),
                            'alternate_comment' => null,
                            'values' => [],
                        ];
                    } else {
                        $property = $api->searchOne('properties', ['term' => $term])->getContent();
                        // In the case the property was removed after the generation.
                        if (empty($property)) continue;
                        $propertyData = [
                            'property' => $property,
                            'alternate_label' => null,
                            'alternate_comment' => null,
                            'values' => [],
                        ];
                    }
                ?>
                    <div class="property">
                        <dt>
                            <?= $propertyData['alternate_label'] ? $escape($propertyData['alternate_label']) : $escape($translate($propertyData['property']->label())) ?>
                            <?php if (!isset($propertyData['property'])):?>
                            <?php // Nothing to do (file). ?>
                            <?php elseif ('term' === $labelInfo): ?>
                            <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
                            <?php elseif ('vocab' === $labelInfo): ?>
                            <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
                            <?php endif; ?>
                        </dt>
                        <div class="values">

                        <?php foreach ($propositions as $key => $proposition):
                            // TODO Manage all types.
                            if (array_key_exists('@uri', $proposition['original'])) {
                                $type = 'uri';
                            } elseif (array_key_exists('@resource', $proposition['original'])) {
                                $type = 'resource';
                            } else {
                                $type = 'literal';
                            }
                            switch ($type):
                            case 'resource':
                                $original = $proposition['original']['@resource'];
                                $proposed = $proposition['proposed']['@resource'];
                                $isValidated = $proposition['validated'];
                                $process = $proposition['process'];

                                try {
                                    /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $originalResource */
                                    $originalResource = $api->read('resources', ['id' => $original])->getContent();
                                } catch (\Omeka\Api\Exception\NotFoundException $e) {
                                    $originalResource = null;
                                }
                                try {
                                    /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $proposedResource */
                                    $proposedResource = $api->read('resources', ['id' => $proposed])->getContent();
                                } catch (\Omeka\Api\Exception\NotFoundException $e) {
                                    $proposedResource = null;
                                }

                                $class = ['value'];
                                if ($isValidated) $class[] = 'validated-value';
                                ?>
                                <div>
                                    <?php if ($process === 'remove'): ?>
                                    <dd class="<?= implode(' ', $class) ?> <?= $originalResource ? $originalResource->resourceName() : '' ?>">
                                        <span data-name="<?= $term . '[' . $key . '][@resource]' ?>" class="remove-value"><?= $originalResource->linkPretty() ?></span>
                                    </dd>
                                    <?php else: ?>
                                        <?php if ($original): ?>
                                    <dd class="<?= implode(' ', $class) ?> <?= $originalResource ? $originalResource->resourceName() : '' ?>">
                                        <span data-name="<?= $term . '[' . $key . '][@resource]' ?>" class="original-value"><?= $originalResource->linkPretty() ?></span>
                                    </dd>
                                        <?php endif; ?>
                                    <dd class="<?= implode(' ', $class) ?> <?= $proposedResource ? $proposedResource->resourceName() : '' ?>">
                                        <span data-name="<?= $term . '[' . $key . '][@resource]' ?>" class="<?= $process ?>-value"><?= $proposedResource ? $proposedResource->linkPretty() : '' ?></span>
                                    </dd>
                                    <?php endif; ?>

                                    <span class="single actions">
                                        <?php if ($isValidated): ?>
                                            <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                                        <?php elseif ($process === 'keep'): ?>
                                            <span class="no-action o-icon-not-validable-value" aria-label="<?= $escapeAttr($translate('Not validable')) ?>"></span>
                                        <?php elseif (!$editRight): ?>
                                            <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escapeAttr($translate('No right to write')) ?>"></span>
                                        <?php else: ?>
                                            <a href="#"
                                                class="validate-value o-icon-validate-value"
                                                data-validate-value-url="<?= $escapeAttr($generatedResource->adminUrl('validate-value') . "?term=$term&key=$key") ?>"
                                                data-status="validate-value"
                                                aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                                                title="<?= $txt ?>"></a>
                                        <?php endif; ?>
                                    </span>

                                </div>
                                 <?php
                                break;

                            case 'uri':
                                $original_uri = $proposition['original']['@uri'];
                                $proposed_uri = $proposition['proposed']['@uri'];
                                $original_label = $proposition['original']['@label'];
                                $proposed_label = $proposition['proposed']['@label'];

                                $isValidated = $proposition['validated'];
                                $process = $proposition['process'];

                                $class = ['value'];
                                if ($isValidated) $class[] = 'validated-value';
                                $language = $proposition['value'] ? $proposition['value']->lang() : null;
                                ?>
                                <dd class="<?= implode(' ', $class) ?>" lang="<?= $escapeAttr($language) ?>">
                                    <?php if ($language): ?>
                                    <span class="language"><?= $escape($language) ?></span>
                                    <?php endif; ?>

                                    <?php if ($process === 'remove'): ?>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_label) ?></span><span>:</span>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_uri) ?></span>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_label) ?></span><span>:</span>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original_uri) ?></span>
                                    <?php else: ?>
                                        <?php if ($original_label): ?>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="original-value"><?= $escape($original_label) ?></span><span>:</span>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="original-value"><?= $escape($original_uri) ?></span>
                                    <br/>
                                        <?php endif; ?>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="<?= $process ?>-value"><?= $escape($proposed_label) ?></span><span>:</span>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="<?= $process ?>-value"><?= $escape($proposed_uri) ?></span>
                                    <?php endif; ?>

                                    <span class="single actions">
                                    <?php if ($isValidated): ?>
                                        <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                                    <?php elseif ($process === 'keep'): ?>
                                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escapeAttr($translate('Not validable')) ?>"></span>
                                    <?php elseif (!$editRight): ?>
                                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escapeAttr($translate('No right to write')) ?>"></span>
                                    <?php else: ?>
                                        <a href="#"
                                            class="validate-value o-icon-validate-value"
                                            data-validate-value-url="<?= $escapeAttr($generatedResource->adminUrl('validate-value') . "?term=$term&key=$key") ?>"
                                            data-status="validate-value"
                                            aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                                            title="<?= $txt ?>"></a>
                                    <?php endif; ?>
                                    </span>
                                </dd>
                                <?php
                                break;

                            case 'literal':
                            default:
                                $original = $proposition['original']['@value'];
                                $proposed = $proposition['proposed']['@value'];
                                $isValidated = $proposition['validated'];
                                $process = $proposition['process'];

                                $class = ['value'];
                                if ($isValidated) $class[] = 'validated-value';
                                $language = $proposition['value'] ? $proposition['value']->lang() : null;
                                ?>
                                <dd class="<?= implode(' ', $class) ?>" lang="<?= $escapeAttr($language) ?>">
                                    <?php if ($language): ?>
                                    <span class="language"><?= $escape($language) ?></span>
                                    <?php endif; ?>

                                    <?php if ($process === 'remove'): ?>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="remove-value"><?= $escape($original) ?></span>
                                    <?php else: ?>
                                        <?php if ($original): ?>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="original-value"><?= $escape($original) ?></span>
                                    <br/>
                                        <?php endif; ?>
                                    <span data-name="<?= $term . '[' . $key . '][@value]' ?>" class="<?= $process ?>-value"><?= $escape($proposed) ?></span>
                                    <?php endif; ?>

                                    <span class="single actions">
                                    <?php if ($isValidated): ?>
                                        <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                                    <?php elseif ($process === 'keep'): ?>
                                        <span class="no-action o-icon-not-validable-value" aria-label="<?= $escapeAttr($translate('Not validable')) ?>"></span>
                                    <?php elseif (!$editRight): ?>
                                        <span class="no-action o-icon-validate-value no-right" aria-label="<?= $escapeAttr($translate('No right to write')) ?>"></span>
                                    <?php else: ?>
                                        <a href="#"
                                            class="validate-value o-icon-validate-value"
                                            data-validate-value-url="<?= $escapeAttr($generatedResource->adminUrl('validate-value') . "?term=$term&key=$key") ?>"
                                            data-status="validate-value"
                                            aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                                            title="<?= $txt ?>"></a>
                                    <?php endif; ?>

                                    </span>
                                </dd>
                                 <?php
                                break;
                            endswitch;
                        endforeach;
                        ?>
                        </div>
                    </div>
                <?php endforeach; ?>
                </dl>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php endif; ?>

</div>
