<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$setting = $plugins->get('setting');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$canGenerate = $plugins->get('canGenerate');
?>

<ul>
    <li>
        <?= $hyperlink(
            $translate('See generations'), // @translate
            $url('site/guest/generation', [], true)
        ) ?>
    </li>
    <?php if ($canGenerate): ?>
    <li>
        <?= $hyperlink(
            $translate('Add a new record'),
            $url('site/guest/generation', ['action' => 'add'], true))
        ?>
    </li>
    <?php endif; ?>
</ul>
