<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Generate\Api\Representation\GenerationRepresentation[] $generations
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$generationLink = $plugins->get('generationLink');
$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;
$guestNavigation = $user && $plugins->has('guestNavigation') ? $plugins->get('guestNavigation')() : null;

$hasGuestNav = $guestNavigation && $guestNavigation->getContainer()->count();

$this->vars()->offsetSet('skipGenerateCss', false);
$partial('generate/site/generation/asset-include');
$siteSlug = $this->params()->fromRoute('site-slug');

$this->htmlElement('body')->appendAttribute('class', 'generation resource browse');
?>

<?php if ($breadcrumbs && !$hasGuestNav): ?>
<?= $breadcrumbs() ?>
<?php endif; ?>

<?php if ($hasGuestNav): ?>
<nav class="navigation-guest">
    <?= $guestNavigation->menu()->renderMenu() ?>
</nav>
<?php endif; ?>

<?= $this->pageTitle($translate('Generations'), 2) // @translate ?>

<?php if (count($generations)): ?>
<h3><?= sprintf($translate('%d generations'), count($generations)) // @translate ?></h3>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list generation-list">
    <?php foreach ($generations as $generation): ?>
    <li class="resource generation">
        <?= sprintf('Generation #%d (%s)', $generation->id(), $i18n->dateFormat($generation->created(), 'medium', 'medium')) ?>
        <h4><?= $hyperlink($generation->displayTitle(), $generation->siteUrl($siteSlug, false, 'show', true)) ?></h4>
        <ul class="generation-status">
            <li class="generation-resource"><?= $generation->resource() ? $generation->resource()->linkPretty() : $escape($translate('No resource')) ?></li>
            <li class="submitted"><?= $escape($generation->isSubmitted() ? $translate('Is submitted') : $translate('Is not submitted')) ?></li>
            <li class="reviewed"><?= $escape($generation->isReviewed() ? $translate('Is reviewed') : $translate('Is not reviewed')) ?></li>
        </ul>
        <?php if ($generation->isUpdatable()): ?>
        <ul class="actions" data-message-remove-generation="<?= $escapeAttr($translate('Are you sure to remove this generation?')) ?>">
            <?php if ($generation->userIsAllowed('update')): ?>
            <li><a class="o-icon-edit button edit-button edit-generation" href="<?= $escapeAttr($generation->siteUrl($siteSlug, 'edit', false, true)) ?>"><?= $escape($translate('Edit')) ?></a></li>
            <?php endif; ?>
            <?php if ($generation->userIsAllowed('delete')): ?>
            <li><a class="o-icon-delete button delete-button remove-generation" data-generation-id="<?= $generation->id() ?>" data-generation-url="<?= $escapeAttr($generation->siteUrl($siteSlug, false, 'delete', true)) ?>" data-redirect-url="<?= $escapeAttr($url('site/guest/generation', ['action' => 'browse'], true)) ?>" href="#"><?= $escape($translate('Delete')) ?></a></li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<p class="noresults">
    <?= $translate('There are no generations.') // @translate ?>
</p>
<?php endif; ?>
<div>
    <?= $generationLink() ?>
</div>
